#!/bin/bash

case $1 in
	left) xmodmap -e "pointer = 3 2 1" >& /dev/null && echo 'Set to lefthand mode';;
	right) xmodmap -e "pointer = 1 2 3" >& /dev/null && echo 'Set to righthand mode';;
	*) echo "'setmouse left' for lefthanded mouse buttons, right for righthanded" ;;
esac
